ARG IMAGE_REGISTRY_PREFIX=docker.m.daocloud.io/library/
FROM ${IMAGE_REGISTRY_PREFIX}node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

ARG IMAGE_REGISTRY_PREFIX=docker.m.daocloud.io/library/
FROM ${IMAGE_REGISTRY_PREFIX}nginx:alpine
COPY nginx.compose.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
